# Generated by Django 5.1.1 on 2024-10-08 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect29", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deliverable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("P", "Pendiente"),
                            ("R", "Revisado"),
                            ("A", "Aprobado"),
                            ("D", "Desaprobado"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("fecha_creacion", models.DateField(auto_now_add=True)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("PM", "Project Management"),
                            ("SI", "Software Implementation"),
                        ],
                        max_length=2,
                    ),
                ),
                ("actividad", models.CharField(max_length=200)),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="connect29.project",
                    ),
                ),
            ],
        ),
    ]
