# Generated by Django 5.1.1 on 2024-10-09 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("connect29", "0002_deliverable"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deliverable",
            old_name="proyecto",
            new_name="project",
        ),
    ]
