# Generated by Django 5.1.1 on 2024-10-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect29", "0003_rename_proyecto_deliverable_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverable",
            name="codigo",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
