# Generated by Django 5.1.1 on 2024-10-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect29", "0004_deliverable_codigo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverable",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Pendiente", "Pendiente"),
                    ("Revisado", "Revisado"),
                    ("Aprobado", "Aprobado"),
                    ("Desaprobado", "Desaprobado"),
                ],
                default="Pendiente",
                max_length=20,
            ),
        ),
    ]
